markdown: rdiscount
highlighter: rouge
permalink: /posts/:title
rdiscount:
  extensions: [smart]
paginate: 5


name: Ian Mackenzie Whalen
url: http://ianwhalen.com
description: 
GitHub: IanWhalen
Flickr: IanWhalen
LinkedIn: IanWhalen
gravatar_url: http://gravatar.com/avatar/6e33ce2ed935a5bbe1f7b8a60d6c13e7

gems: [jekyll-paginate]
